---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[habitat_workstation::default]
    verifier:
      inspec_tests:
        - test/integration/default_test.rb
        - test/integration/docker_compose_test.rb
    attributes:
      hab:
        version: none
  - name: install_hab
    run_list:
      - recipe[habitat_workstation::default]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
      hab:
        version: some_value_that_is_not_the_string_none
