---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-17.10
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[sysdig_workstation::default]
    verifier:
      inspec_tests:
        - test/integration/default_test.rb
        - test/integration/docker_compose_test.rb
